# Meta Data for SEO

## Homepage
title = "Esc.sh"
#titleSeparator = "-"
description = "A collection of random notes from an Engineer"

AuthorName = 'Mansoor'

## Open Graph + Twitter Cards
#images = ["doks.png"]
twitterSite = "esc_sh"
twitterCreator = "esc_sh"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
# schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/esc_sh"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/mansoormajeed"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>"


# Edit Page
docsRepo = "https://github.com/mansoormajeed/esc.sh-hugo"
docsRepoBranch = "master"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
