baseurl = "https://esc.sh"
title = "Esc.sh"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Mansoor"
  info = "Site Reliability Engineer"
  description = "Mansoor's personal website"
  keywords = "blog,sre,devops,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mansoormajeed/"



# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

